#!/bin/sh

mysql -uroot -p"${DOCKER_DB_PASSWORD}" <<MYSQL_SCRIPT
CREATE USER IF NOT EXISTS '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
MYSQL_SCRIPT
